feat(#8685utq2d) Implement Ontology Mapping Gap Detection
mapped/mapped-willow-mapping pull request #39
Opened 2023-10-02 23:56 UTC by connorjcantrell

This PR introduces functionality to load and process ontologies from their respective NuGet, parse DTDL, parse their mappings, and detect gaps in the mappings.

Key Features:
- Load ontologies for both `mapped.ontologies.core.dtdl` and `willowinc.ontology.dtdlv3` NuGet packages
- Parse respective mappings from `Ontologies.Mappings` source.
- Identify gaps in the mappings for both ontologies.
- Output missing gaps to a `mapping_gaps.json` file.

Changes:
- Main execution logic added in `main.py`.
- Introduced `DTDLHandler` class in `handler.py` to handle ontology processing.
- New modules added under the `modules` directory for more granular functionalities.
  - Introduced `mappings` and `ontology` sub-modules for respective features.

2023-10-03 00:00 UTC, connorjcantrell commented
@jbkoh This PR currently identifies which concepts are not represented in the mapping files. However, it doesn't identify gaps between the two mapping files. If you would like to include this ability, we could migrate https://github.com/mapped/contrast into this repository.

2023-10-03 23:06 UTC, jbkoh requested changes
The code looks good overall. Please update the github action to include the output of this as an artifact.

2023-10-03 23:06 UTC, jbkoh commented on scripts/mapping_diagnostics/main.py
> +
```python
if __name__ == '__main__':
  main()
```
is the common convention for this

2023-10-03 23:06 UTC, jbkoh requested changes
The code looks good overall. Please update the github action to include the output of this as an artifact.

2023-10-03 23:08 UTC, jbkoh commented
just a quick comment that `modules` is an unnecessary level.

2023-10-04 16:35 UTC, connorjcantrell commented on .github/workflows/Ontology_Mappings_Diagnostics.yml
> +    - run: poetry install
@jbkoh I'm having trouble with using my installed dependencies within the GH action. Poetry shell doesn't work.

2023-10-04 20:47 UTC, connorjcantrell reviewed
fixed

2023-10-04 21:01 UTC, jbkoh approved these changes

2023-10-04 21:10 UTC, merged